version: "3"

services:
  # Service pour l'API de Projet 7
  projet7api:
    image: api_docker
    container_name: projet7api
    restart: unless-stopped
    networks:
      - projet7-net  # Utilise le réseau "projet7-net" pour la communication

  # Service pour le tableau de bord de Projet 7
  projet7dashboard:
    image: dashboard_docker
    container_name: projet7dashboard
    restart: unless-stopped
    ports:
      - 80:80  # Mappe le port 80 du conteneur au port 80 de l'hôte
    networks:
      - projet7-net  # Utilise le réseau "projet7-net" pour la communication

networks:
  projet7-net:
    external: false
