version: "3"

services:
  # Service pour l'API de Projet 7
  projet7api:
    image: api_docker
    container_name: projet7api
    restart: unless-stopped
    volumes:
      - ./api_data:/app:rw
    networks:
      - projet7-net  # Utilise le réseau "projet7-net" pour la communication

  # Service pour le tableau de bord de Projet 7
  projet7dashboard:
    image: dashboard_docker
    container_name: projet7dashboard
    restart: unless-stopped
    volumes:
      - ./dashboard_data:/app:rw
    environment:
      - STREAMLIT_SERVER_PORT=80
    networks:
      - projet7-net  # Utilise le réseau "projet7-net" pour la communication
      - services-net

networks:
  services-net:
    external: true
  projet7-net:
    external: false
