version: "3"

services:
  # Service pour l'API de Projet 7
  projet7API:
    image: monappregistrywd.azurecr.io/api_docker
    container_name: projet7api
    restart: unless-stopped
    networks:
      - projet7-net  # Utilise le réseau "projet7-net" pour la communication

  # Service pour le tableau de bord de Projet 7
  projet7Dashboard:
    image: monappregistrywd.azurecr.io/dashboard_docker
    container_name: projet7dashboard
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_PORT=80
    ports:
      - 80:80  # Mappe le port 80 du conteneur au port 80 de l'hôte
    networks:
      - projet7-net  # Utilise le réseau "projet7-net" pour la communication

networks:
  projet7-net:
    external: false
