name: Deploy on Push

on:
  push:
    branches:
      - main  # Déclencher le déploiement uniquement depuis la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.WILLIAM_DAVID_KEY }}
        known_hosts: 'placeholder...'

    - name: Adding Known Hosts
      run: ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to server
      run: ssh -p ${{ secrets.PORT }} william@${{ secrets.SERVER }} 'cd /home/william/Projet_7_Prod && git pull origin main'
